# Generated by Django 3.2.25 on 2025-03-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='page_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
