# Generated by Django 3.2.25 on 2025-03-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20250315_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='banner_alt_text',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
