# Generated by Django 3.2.25 on 2025-03-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Enquiries'},
        ),
    ]
