# Generated by Django 3.2.25 on 2025-03-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='summary',
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='page_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
