# Generated by Django 3.2.25 on 2025-03-14 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20250312_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='track_quantity',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('course', 'Courses'), ('event', 'Events')], default='Furniture', max_length=64),
        ),
    ]
